sudo: required
services:
  - docker

before_install:
  - docker build -t shengchuang/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run shengchuang96/react-test npm test -- --coverage

after_success:
  - docker build -t shengchuang96/multi-client ./client
  - docker build -t shengchuang96/multi-nginx ./nginx
  - docker build -t shengchuang96/multi-server ./server
  - docker build -t shengchuang96/multi-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --pasword-stdin
  # Take those images and push them to docker hub
  - docker push shengchuang96/multi-client
  - docker push shengchuang96/multi-nginx
  - docker push shengchuang96/multi-server
  - docker push shengchuang96/multi-worker